<a href="https://colab.research.google.com/github/imammarzuki/Eksperimen/blob/main/CF_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-surprise

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp310-cp310-linux_x86_64.whl size=3162985 sha256=ed779909caad71321134baa7ec85c9c36205a3328f525c7fe5de3f0c38e845f4
  Stored in directory: /root/.cache/pip/wheels/a5/ca/a8/4e28def53797fdc4363ca4af740db15a9c2f1595ebc51fb445
Successfully built scikit-surprise


In [2]:
from surprise import Dataset, Reader
from surprise import SVD, accuracy
from surprise.model_selection import train_test_split
import numpy as np
from sklearn.metrics import confusion_matrix, mean_absolute_error, mean_squared_error
import pandas as pd

In [3]:
# Contoh data: user_id, item_id, rating1, rating2, ... (multi-criteria)
data = {
    'user_id': [1, 1, 2, 2, 3, 3, 4, 4],
    'item_id': [101, 102, 101, 103, 102, 104, 101, 104],
    'rating1': [3, 2, 4, 3, 1, 5, 5, 4],
    'rating2': [2, 4, 3, 5, 3, 4, 4, 2]
}

df = pd.DataFrame(data)
# Menggabungkan beberapa rating menjadi satu dengan rata-rata (sederhana)
df['rating'] = df[['rating1', 'rating2']].mean(axis=1)

# Load data ke Surprise
reader = Reader(rating_scale=(1, 5))
data = Dataset.load_from_df(df[['user_id', 'item_id', 'rating']], reader)

In [4]:
# Memecah data menjadi train dan test set
trainset, testset = train_test_split(data, test_size=0.25)

# Menggunakan SVD sebagai algoritma Collaborative Filtering
algo = SVD()

# Melatih model
algo.fit(trainset)

# Membuat prediksi pada test set
predictions = algo.test(testset)

In [5]:
# Menghitung RMSE dan MAE
rmse = accuracy.rmse(predictions)
mae = accuracy.mae(predictions)

# Menghitung Confusion Matrix (mengasumsikan rating dibulatkan)
actual = np.array([pred.r_ui for pred in predictions])
predicted = np.array([round(pred.est) for pred in predictions])
actual = np.where( actual >= 0.5, 1, 0)
cm = confusion_matrix(actual, predicted, labels=[1, 2, 3, 4, 5])

print("MAE:", mae)
print("RMSE:", rmse)
print("Confusion Matrix:\n", cm)

RMSE: 1.5738
MAE:  1.5676
MAE: 1.5675554899633837
RMSE: 1.5738139541920204
Confusion Matrix:
 [[0 0 2 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
