<a href="https://colab.research.google.com/github/imammarzuki/Eksperimen/blob/main/Hybrid_CF_KNN_dan_CBF_TFIDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install scikit-surprise

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp310-cp310-linux_x86_64.whl size=2357239 sha256=0e188c6454469ef432344990ec07b98f45bc22f362629370349b4960e3872798
  Stored in directory: /root/.cache/pip/wheels/4b/3f/df/6acbf0a40397d9bf3ff97f582cc22fb9ce66adde75bc71fd54
Successfully built scikit-surprise


In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics import mean_absolute_error, mean_squared_error, confusion_matrix
from surprise import Dataset, Reader, KNNBasic
from surprise.model_selection import train_test_split
from surprise import accuracy

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
place=pd.read_csv("drive/MyDrive/S3/Eksperimen/Data/tourism_with_id.csv")
rating=pd.read_csv("drive/MyDrive/S3/Eksperimen/Data/tourism_rating.csv")
user=pd.read_csv("drive/MyDrive/S3/Eksperimen/Data/user.csv")

In [ ]:
place.columns

Index(['Place_Id', 'Place_Name', 'Description', 'Category', 'City', 'Price',
       'Rating', 'Time_Minutes', 'Coordinate', 'Lat', 'Long', 'Unnamed: 11',
       'Unnamed: 12'],
      dtype='object')

In [ ]:
place1=place[["Place_Id", "Place_Name", "Description", "City", "Price", "Rating"]]

In [ ]:
place1.columns

Index(['Place_Id', 'Place_Name', 'Description', 'City', 'Price', 'Rating'], dtype='object')

In [ ]:
place2=place1[place1["City"]=="Surabaya"]
place2

Place_Id                                 Place_Name  \
391       392                Ekowisata Mangrove Wonorejo   
392       393                      Taman Harmoni Keputih   
393       394                          Air Mancur Menari   
394       395                             Taman Prestasi   
395       396                        Monumen Kapal Selam   
396       397                        Taman Kunang-Kunang   
397       398                        Taman Buah Surabaya   
398       399                              Taman Pelangi   
399       400                        Hutan Bambu Keputih   
400       401                             Taman Keputran   
401       402                Food Junction Grand Pakuwon   
402       403                           Taman Barunawati   
403       404                              Kenjeran Park   
404       405                        Surabaya North Quay   
405       406                       Kebun Bibit Wonorejo   
406       407            Taman Ekspresi Dan Perpustakaan   
407       408                    Kebun Binatang Surabaya   
408       409                                Rumah Batik   
409       410                          Ciputra Waterpark   
410       411                  Masjid Muhammad Cheng Hoo   
411       412                   Masjid Nasional Al-Akbar   
412       413              Museum TNI AL Loka Jala Crana   
413       414                             Jembatan Merah   
414       415                    Museum De Javasche Bank   
415       416                           Keraton Surabaya   
416       417                     Klenteng Sanggar Agung   
417       418      Museum Sepuluh Nopember Kota Surabaya   
418       419                      Monumen Tugu Pahlawan   
419       420             Surabaya Museum (Gedung Siola)   
420       421              Museum Kesehatan Dr. Adhyatma   
421       422                 Monumen Jalesveva Jayamahe   
422       423                      Patung Sura dan Buaya   
423       424                        Pantai Ria Kenjeran   
424       425                Waterpark Kenjeran Surabaya   
425       426                        Balai Kota Surabaya   
426       427                   Patung Buddha Empat Rupa   
427       428             Monumen Bambu Runcing Surabaya   
428       429                         House of Sampoerna   
429       430                     Atlantis Land Surabaya   
430       431                       Taman Hiburan Rakyat   
431       432                                Taman Mundu   
432       433                        Museum Mpu Tantular   
433       434                              Taman Bungkul   
434       435           Taman Air Mancur Menari Kenjeran   
435       436               Taman Flora Bratang Surabaya   
436       437  Gereja Perawan Maria Tak Berdosa Surabaya   

                                           Description      City   Price  \
391  Hutan Wisata Mangrove Surabaya merupakan wisat...  Surabaya       0   
392  Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya       0   
393  Jembatan Kenjeran dengan air mancur menarinya ...  Surabaya   35000   
394  Taman Prestasi Surabaya merupakan salah satu t...  Surabaya       0   
395  Monumen Kapal Selam, atau disingkat Monkasel, ...  Surabaya   15000   
396  Taman Kunang – Kunang di Surabaya ini mempunya...  Surabaya       0   
397  Wisata Taman Buah Undaan di Surabaya adalah sa...  Surabaya       0   
398  Kalau pelangi biasanya ada di siang hari pasca...  Surabaya       0   
399  Surabaya menjadi kota metropolitan kedua setel...  Surabaya       0   
400  Ntah, mengapa nama taman ini disebut dengan ta...  Surabaya       0   
401  Food Junction Grand Pakuwon sebetulnya merupak...  Surabaya       0   
402  Taman Barunawati yang lokasinya berada di kota...  Surabaya       0   
403  Kenjeran Park merupakan salah satu tempat wisa...  Surabaya   35000   
404  Surabaya menjadi kota besar yang sering menjad...  Surabaya   50000   
405  Meskipun namanya kebun bibit, namun kaw

In [ ]:
place2=place2.reset_index(drop=True)
place2

Place_Id                                 Place_Name  \
0        392                Ekowisata Mangrove Wonorejo   
1        393                      Taman Harmoni Keputih   
2        394                          Air Mancur Menari   
3        395                             Taman Prestasi   
4        396                        Monumen Kapal Selam   
5        397                        Taman Kunang-Kunang   
6        398                        Taman Buah Surabaya   
7        399                              Taman Pelangi   
8        400                        Hutan Bambu Keputih   
9        401                             Taman Keputran   
10       402                Food Junction Grand Pakuwon   
11       403                           Taman Barunawati   
12       404                              Kenjeran Park   
13       405                        Surabaya North Quay   
14       406                       Kebun Bibit Wonorejo   
15       407            Taman Ekspresi Dan Perpustakaan   
16       408                    Kebun Binatang Surabaya   
17       409                                Rumah Batik   
18       410                          Ciputra Waterpark   
19       411                  Masjid Muhammad Cheng Hoo   
20       412                   Masjid Nasional Al-Akbar   
21       413              Museum TNI AL Loka Jala Crana   
22       414                             Jembatan Merah   
23       415                    Museum De Javasche Bank   
24       416                           Keraton Surabaya   
25       417                     Klenteng Sanggar Agung   
26       418      Museum Sepuluh Nopember Kota Surabaya   
27       419                      Monumen Tugu Pahlawan   
28       420             Surabaya Museum (Gedung Siola)   
29       421              Museum Kesehatan Dr. Adhyatma   
30       422                 Monumen Jalesveva Jayamahe   
31       423                      Patung Sura dan Buaya   
32       424                        Pantai Ria Kenjeran   
33       425                Waterpark Kenjeran Surabaya   
34       426                        Balai Kota Surabaya   
35       427                   Patung Buddha Empat Rupa   
36       428             Monumen Bambu Runcing Surabaya   
37       429                         House of Sampoerna   
38       430                     Atlantis Land Surabaya   
39       431                       Taman Hiburan Rakyat   
40       432                                Taman Mundu   
41       433                        Museum Mpu Tantular   
42       434                              Taman Bungkul   
43       435           Taman Air Mancur Menari Kenjeran   
44       436               Taman Flora Bratang Surabaya   
45       437  Gereja Perawan Maria Tak Berdosa Surabaya   

                                          Description      City   Price  \
0   Hutan Wisata Mangrove Surabaya merupakan wisat...  Surabaya       0   
1   Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya       0   
2   Jembatan Kenjeran dengan air mancur menarinya ...  Surabaya   35000   
3   Taman Prestasi Surabaya merupakan salah satu t...  Surabaya       0   
4   Monumen Kapal Selam, atau disingkat Monkasel, ...  Surabaya   15000   
5   Taman Kunang – Kunang di Surabaya ini mempunya...  Surabaya       0   
6   Wisata Taman Buah Undaan di Surabaya adalah sa...  Surabaya       0   
7   Kalau pelangi biasanya ada di siang hari pasca...  Surabaya       0   
8   Surabaya menjadi kota metropolitan kedua setel...  Surabaya       0   
9   Ntah, mengapa nama taman ini disebut dengan ta...  Surabaya       0   
10  Food Junction Grand Pakuwon sebetulnya merupak...  Surabaya       0   
11  Taman Barunawati yang lokasinya berada di kota...  Surabaya       0   
12  Kenjeran Park merupakan salah satu tempat wisa...  Surabaya   35000   
13  Surabaya menjadi kota besar yang sering menjad...  Surabaya   50000   
14  Meskipun namanya kebun bibit, namun kawasan in...  Surabaya       0   
15  Taman Ekspresi Surabaya ti

In [ ]:
place2.columns

Index(['Place_Id', 'Place_Name', 'Description', 'City', 'Price', 'Rating'], dtype='object')

In [ ]:
rating.columns

Index(['User_Id', 'Place_Id', 'Place_Ratings'], dtype='object')

In [ ]:
user.columns

Index(['User_Id', 'Location', 'Age'], dtype='object')

In [ ]:
data1=pd.merge(rating, place2, on="Place_Id")
data1.head()

User_Id  Place_Id  Place_Ratings             Place_Name  \
0        1       393              5  Taman Harmoni Keputih   
1        6       393              2  Taman Harmoni Keputih   
2        8       393              5  Taman Harmoni Keputih   
3       19       393              3  Taman Harmoni Keputih   
4       27       393              3  Taman Harmoni Keputih   

                                         Description      City  Price  Rating  
0  Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya      0     4.4  
1  Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya      0     4.4  
2  Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya      0     4.4  
3  Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya      0     4.4  
4  Tempat tersebut ialah Taman Hatmoni Keputih Su...  Surabaya      0     4.4

In [ ]:
data2=data1.rename({"User_Id":"user_id", "Place_Id":"place_id",  "Place_Ratings":"rating1", "Place_Name":"place_name", "Description":"description","Price":"price", "Rating":"rating2"}, axis=1)

In [ ]:
data2.columns

Index(['user_id', 'place_id', 'rating1', 'place_name', 'description', 'City',
       'price', 'rating2'],
      dtype='object')

In [ ]:
df=data2[["user_id","place_id", "place_name", "description", "price", "rating1", "rating2"]]

In [ ]:
df.head()

user_id  place_id             place_name  \
0        1       393  Taman Harmoni Keputih   
1        6       393  Taman Harmoni Keputih   
2        8       393  Taman Harmoni Keputih   
3       19       393  Taman Harmoni Keputih   
4       27       393  Taman Harmoni Keputih   

                                         description  price  rating1  rating2  
0  Tempat tersebut ialah Taman Hatmoni Keputih Su...      0        5      4.4  
1  Tempat tersebut ialah Taman Hatmoni Keputih Su...      0        2      4.4  
2  Tempat tersebut ialah Taman Hatmoni Keputih Su...      0        5      4.4  
3  Tempat tersebut ialah Taman Hatmoni Keputih Su...      0        3      4.4  
4  Tempat tersebut ialah Taman Hatmoni Keputih Su...      0        3      4.4

In [ ]:
# Menggabungkan rating menjadi satu nilai rata-rata
df['average_rating'] = df[['rating1', 'rating2']].mean(axis=1)

In [ ]:
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(df['description'])

# Menghitung cosine similarity matrix
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [ ]:
# Data untuk CF
reader = Reader(rating_scale=(1, 10))
data = Dataset.load_from_df(df[['user_id', 'place_id', 'average_rating']], reader)
trainset, testset = train_test_split(data, test_size=0.25)

# Menggunakan KNN
algo = KNNBasic(sim_options={'name': 'cosine', 'user_based': True})
algo.fit(trainset)
predictions = algo.test(testset)

Computing the cosine similarity matrix...
Done computing similarity matrix.


In [ ]:
# Prediksi CF
cf_predictions = np.array([pred.est for pred in predictions])

# Gabungkan dengan CBF
final_predictions = []
for pred in predictions:
    place_idx = df[df['place_id'] == pred.iid].index[0]
    cbf_score = np.mean(cosine_sim[place_idx])
    final_score = (cbf_score + pred.est) / 2
    final_predictions.append(final_score)

# Actual ratings
actual_ratings = np.array([pred.r_ui for pred in predictions])

# Hitung metrik
mae = mean_absolute_error(actual_ratings, final_predictions)
rmse = np.sqrt(mean_squared_error(actual_ratings, final_predictions))
cm = confusion_matrix(actual_ratings.round(), np.array(final_predictions).round())

print(f"MAE: {mae}")
print(f"RMSE: {rmse}")
print("Confusion Matrix:\n", cm)

MAE: 1.8232905599999851
RMSE: 1.9607677308727087
Confusion Matrix:
 [[  0   0   0   0   0]
 [  0   0   0   0   0]
 [  0 102   0   0   0]
 [  3 101   0   0   0]
 [  3  54   0   0   0]]
